FROM node:lts-alpine AS build

WORKDIR /usr/src/app

ENV NODE_ENV production

COPY . .

RUN npm ci --only=production

RUN CI=true npm test

RUN npm run build

EXPOSE 3000

FROM nginx:1.21-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html