version: '3'
services:
  frontend:
    image: app-frontend
    container_name: app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    env_file: .env

  backend:
    image: app-backend
    restart: always
    container_name: app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
       - ./backend:/usr/src/app
       - /usr/src/app/node_modules
    ports:
      - 3001:3001
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - PGHOST=database
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  debug:
    image: busybox
    container_name: debug

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nging.conf:\etc\nginx\nginx.conf:ro
    ports:
     - 8080:80
    depends_on:
     - frontend
     - backend

volumes:
  pgdata:
