name: Deployment pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install
        run: npm install
      - name: lint
        run: npm run eslint
    ##
    # - name: test
    #   run: npm run test
    # - name: e2e tests
    #   uses: cypress-io/github-action@v3
    #   with:
    #     command: npm run test:e2e
    #     build: npm run build
    #     start: npm run start-prod
    #     wait-on: http://localhost:3000
    ##
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES"
      - name: heroku deploy
        if: ${{ github.event_name == 'push '}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_ID}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://${{secrets.HEROKU_APP_ID}}.herokuapp.com/health
          checkstring: 'ok'
          delay: 5
          rollbackonhealthcheckfailed: true
  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deptch: "0"
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch